### PR TITLE
Ensure triggering sensor is included in alarm payload even when delay configured

### LINKED ISSUE #38: Delayed alarm not showing trigger source in payload.
> One question - when the alarm is triggered and the delay expires, I am seeing the following payload on the `AlarmTriggered` node;
> 
> image
> 
> Should `source` be populated with something? I was expecting to see a reference to the sensor that triggered the alarm. Or is that only populated for HomeKit style integration?

Hmm, yes it should. This was an extension someone submitted, so not sure why it doesn’t work with a delay node. I might be able to find some time in the next few weeks to look into it, as it is useful, but it should have the name of the trigger node in it I believe.

Thanks for reporting it.

_Originally posted by @macinspak in https://github.com/Anamico/node-red-contrib-alarm/issues/37#issuecomment-1134011864_

### PR DESCRIPTION
**Pull request by sumnerboy12**
Fixes #38

### CODE REVIEW

**Comment by sumnerboy12** [comment]
@macinspak any chance we could get this merged?

**Comment by macinspak** [comment]
Published as 1.3.0, please confirm all working for you guys.

Thanks for the PR and apologies for the delay.

**Comment by sumnerboy12** [comment]
Happy to contribute - thanks for the great node!

**Comment by sumnerboy12** [comment]
@macinspak I see that v1.3.0 is showing on [npmjs](https://www.npmjs.com/package/node-red-contrib-alarm) but it is still only v1.2.5 on [NodeRED](https://flows.nodered.org/node/node-red-contrib-alarm).

How long does it take to update, or is there a manual step needed?

**Comment by macinspak** [comment]
Sorry, forgot to hit the button to check for updates

**Pull request merged**
